use anchor_lang::prelude::*;
use arcium_anchor::prelude::*;

/// Computation definition offset for `validate_trade`.
/// Generated by: comp_def_offset("validate_trade")
const COMP_DEF_OFFSET_VALIDATE_TRADE: u32 = comp_def_offset("validate_trade");

declare_id!("ELMPrpXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

/// ELEMPerp MXE — Confidential Perpetuals on Solana × Arcium
///
/// This Anchor program acts as the MXE (MPC eXecution Environment) for
/// ELEMPerp's encrypted trade lifecycle. It:
///   1. Receives encrypted trade parameters from the client
///   2. Queues the validate_trade computation in Arcium's mempool
///   3. Receives the callback when MPC nodes finish computing
///   4. Emits an event with the encrypted result for the client to decrypt
///
/// Architecture:
///   Client browser → this program → Arcium program → MPC cluster
///                                                   ↓ callback
///                                ← TradeValidatedEvent ←
#[arcium_program]
pub mod elemperp_mxe {
    use super::*;

    /// One-time initialization of the validate_trade computation definition.
    /// Must be called once after deployment before any trades can be queued.
    /// The computation definition account stores the compiled Arcis circuit.
    pub fn init_validate_trade_comp_def(
        ctx: Context<InitValidateTradeCompDef>,
    ) -> Result<()> {
        init_comp_def(ctx.accounts, None, None)?;
        Ok(())
    }

    /// Queue an encrypted trade validation computation.
    ///
    /// Parameters (all encrypted by the client via RescueCipher):
    ///   computation_offset — random u64 seeding the computation PDA
    ///   encrypted_size     — trade size in USDC × 1e6, RescueCipher ciphertext [u8; 32]
    ///   encrypted_leverage — leverage multiplier × 1e6, ciphertext [u8; 32]
    ///   encrypted_direction — 1_000_000 = long, 0 = short, ciphertext [u8; 32]
    ///   encrypted_stop_loss — stop loss price × 1e6, ciphertext [u8; 32]
    ///   encrypted_take_profit — take profit price × 1e6, ciphertext [u8; 32]
    ///   pub_key            — client's ephemeral x25519 public key [u8; 32]
    ///   nonce              — 16-byte CTR nonce as u128 (little-endian)
    ///   mark_price         — current oracle mark price × 1e6 (public, not encrypted)
    pub fn validate_trade(
        ctx: Context<ValidateTrade>,
        computation_offset:      u64,
        encrypted_size:          [u8; 32],
        encrypted_leverage:      [u8; 32],
        encrypted_direction:     [u8; 32],
        encrypted_stop_loss:     [u8; 32],
        encrypted_take_profit:   [u8; 32],
        pub_key:                 [u8; 32],
        nonce:                   u128,
        mark_price:              u64,
    ) -> Result<()> {
        // Build the ArgBuilder payload matching our Arcis circuit's inputs:
        //   validate_trade(inputs: Enc<Shared, TradeInputs>, mark_price: u64)
        //
        // For Enc<Shared, T>: x25519_pubkey + nonce first, then ciphertexts
        // For plaintext u64: plaintext_u64
        let args = ArgBuilder::new()
            .x25519_pubkey(pub_key)         // client's x25519 public key
            .plaintext_u128(nonce)          // CTR nonce (16 bytes as u128 LE)
            .encrypted_u64(encrypted_size)
            .encrypted_u64(encrypted_leverage)
            .encrypted_u64(encrypted_direction)
            .encrypted_u64(encrypted_stop_loss)
            .encrypted_u64(encrypted_take_profit)
            .plaintext_u64(mark_price)      // public oracle price
            .build();

        ctx.accounts.sign_pda_account.bump = ctx.bumps.sign_pda_account;

        // Queue the computation in Arcium's mempool via CPI.
        // The MPC cluster will pick it up, run validate_trade() on encrypted data,
        // and invoke validate_trade_callback() with the encrypted result.
        queue_computation(
            ctx.accounts,
            computation_offset,
            args,
            vec![ValidateTradeCallback::callback_ix(
                computation_offset,
                &ctx.accounts.mxe_account,
                &[],
            )?],
            1, // number of callback transactions
            0, // priority fee in microlamports (0 = default)
        )?;

        msg!(
            "ELEMPerp: trade computation queued. offset={}",
            computation_offset
        );
        Ok(())
    }

    /// Callback invoked by the Arcium program when MPC computation completes.
    ///
    /// The output contains RescueCipher-encrypted TradeOutputs that only
    /// the client (who holds the matching private key) can decrypt.
    /// We emit a Solana event so the client frontend can receive the result.
    #[arcium_callback(encrypted_ix = "validate_trade")]
    pub fn validate_trade_callback(
        ctx: Context<ValidateTradeCallback>,
        output: SignedComputationOutputs<ValidateTradeOutput>,
    ) -> Result<()> {
        let result = match output.verify_output(
            &ctx.accounts.cluster_account,
            &ctx.accounts.computation_account,
        ) {
            Ok(ValidateTradeOutput { field_0 }) => field_0,
            Err(e) => {
                msg!("ELEMPerp: computation error: {}", e);
                return Err(ErrorCode::AbortedComputation.into());
            }
        };

        // Emit encrypted outputs — client decrypts using their private key
        // Output layout from TradeOutputs: [margin, fee, liq_long, liq_short, is_valid]
        emit!(TradeValidatedEvent {
            // Each field is one [u8; 32] RescueCipher ciphertext
            margin:          result.ciphertexts[0],
            fee:             result.ciphertexts[1],
            liq_price_long:  result.ciphertexts[2],
            liq_price_short: result.ciphertexts[3],
            is_valid:        result.ciphertexts[4],
            // Nonce incremented by 1 by MXE (per Arcium docs note)
            nonce:           result.nonce.to_le_bytes(),
        });

        msg!("ELEMPerp: trade validated, result emitted");
        Ok(())
    }
}

/// Event emitted after MPC computation — contains encrypted results.
/// The client uses RescueCipher.decrypt(ciphertext, nonce) to read values.
#[event]
pub struct TradeValidatedEvent {
    pub margin:          [u8; 32],
    pub fee:             [u8; 32],
    pub liq_price_long:  [u8; 32],
    pub liq_price_short: [u8; 32],
    pub is_valid:        [u8; 32],
    pub nonce:           [u8; 16],
}

/// Accounts for validate_trade instruction.
/// Uses #[queue_computation_accounts] macro for Arcium account derivation.
#[queue_computation_accounts("validate_trade", payer)]
#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct ValidateTrade<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(
        init_if_needed,
        space = 9,
        payer = payer,
        seeds = [&SIGN_PDA_SEED],
        bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    #[account(
        mut,
        address = derive_mempool_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    /// CHECK: checked by Arcium program
    pub mempool_account: UncheckedAccount<'info>,
    #[account(
        mut,
        address = derive_execpool_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    /// CHECK: checked by Arcium program
    pub executing_pool: UncheckedAccount<'info>,
    #[account(
        mut,
        address = derive_comp_pda!(computation_offset, mxe_account, ErrorCode::ClusterNotSet)
    )]
    /// CHECK: checked by Arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_VALIDATE_TRADE))]
    pub comp_def_account: Account<'info, ComputationDefinitionAccount>,
    #[account(
        mut,
        address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    pub cluster_account: Account<'info, Cluster>,
    #[account(mut, address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS)]
    pub pool_account: Account<'info, FeePool>,
    #[account(mut, address = ARCIUM_CLOCK_ACCOUNT_ADDRESS)]
    pub clock_account: Account<'info, ClockAccount>,
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

/// Accounts for the compute definition initialization.
#[derive(Accounts)]
pub struct InitValidateTradeCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    /// CHECK: MXE account created by arcium deploy
    #[account(mut, address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    /// CHECK: computation definition account (PDA)
    #[account(
        mut,
        address = derive_comp_def_pda!(COMP_DEF_OFFSET_VALIDATE_TRADE)
    )]
    pub comp_def_account: UncheckedAccount<'info>,
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

/// Accounts for validate_trade_callback — invoked by Arcium after MPC completes.
#[callback_accounts("validate_trade")]
#[derive(Accounts)]
pub struct ValidateTradeCallback<'info> {
    pub arcium_program: Program<'info, Arcium>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_VALIDATE_TRADE))]
    pub comp_def_account: Account<'info, ComputationDefinitionAccount>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    /// CHECK: computation account, verified by Arcium
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Account<'info, Cluster>,
    #[account(address = ::anchor_lang::solana_program::sysvar::instructions::ID)]
    /// CHECK: instructions sysvar
    pub instructions_sysvar: AccountInfo<'info>,
}

#[error_code]
pub enum ErrorCode {
    #[msg("Arcium cluster not set on MXE account")]
    ClusterNotSet,
    #[msg("Arcium computation was aborted")]
    AbortedComputation,
}
